-- AlterTable
ALTER TABLE "StudentAssessment" ADD COLUMN     "meeting1_kehadiran" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "meeting1_kosakata" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "meeting1_membaca" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "meeting1_pengucapan" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "meeting1_speaking" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "meeting2_kehadiran" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "meeting2_kosakata" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "meeting2_membaca" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "meeting2_pengucapan" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "meeting2_speaking" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "meeting3_kehadiran" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "meeting3_kosakata" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "meeting3_membaca" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "meeting3_pengucapan" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "meeting3_speaking" INTEGER NOT NULL DEFAULT 1;
